POST http://localhost:8080/order/add
Content-Type: application/json

{
  "tradeType": "demoData",
  "amount": 1,
  "currency": "demoData",
  "status": "1",
  "channel": "demoData",
  "tradeNo": "demoData",
  "userId": 27,
  "remark": "demoData"
}

###
GET http://localhost:8080/order/?userId=2
Accept: application/json

###
GET http://localhost:8080/clear
Accept: application/json

###

GET http://localhost:8080/move
Accept: application/json

###